### ISSUE TITLE
Publish to pip

### ISSUE THREAD

**Issue by fspoettel** [hija/fotoparadies-status#2]
This tool looks very useful, thanks for creating it! Would you consider publishing it to pip to make install simpler?

**Comment by hija** [comment]
Hey Felix,

good to read you again after such a long time :)

Yes - I definitely consider publishing it to pip. I am going to start the process next week 😃 

Best
Hilko

**Comment by hija** [comment]
Packaged 🎉 

https://pypi.org/project/fotoparadies/

Hope it works :-)

**Comment by fspoettel** [comment]
It does. 👍 Thank you very much!
